version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3.12-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 15s
      retries: 2
      start_period: 20s

  matching-service:
    build: ./matching-service
    ports:
      - '5001:5001'
    env_file:
      - ./matching-service/.env.local
    depends_on:
      rabbitmq:
        condition: service_healthy
