version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - '3001:3001'
    env_file:
      - ./user-service/.env

  question-service:
    build: ./question-service
    ports:
      - '5000:5000'
    env_file:
      - ./question-service/.env.local
