version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - '3001:3001'
    env_file:
      - ./user-service/.env

  question-service:
    build: ./question-service
    ports:
      - '5000:5000'
    env_file:
      - ./question-service/.env.local

  collaboration-service:
    build: ./collaboration-service
    ports:
      - '5555:5555'

  ai-service:
    build: ./ai-service
    ports:
      - '4444:4444'
    env_file:
      - ./ai-service/.env

  rabbitmq:
    image: 'rabbitmq:3.12-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      retries: 5
      start_period: 20s

  matching-service:
    build: ./matching-service
    ports:
      - '5001:5001'
    env_file:
      - ./matching-service/.production.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./api-service/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - question-service
      - collaboration-service
      - matching-service
