apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  db-host: '34.87.128.185'
  db-user: postgres
  db-name: peer-prep
  db-port: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
data:
  db-password: # Insert base64 encoded value
