apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: question
    type: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-deployment
  labels:
    app: question
    type: backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: question
      type: backend
  template:
    metadata:
      labels:
        app: question
        type: backend
    spec:
      containers:
        - name: question
          image: tanchinkiat99/peerprep-question-service:1.4
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: question-secrets
                  key: mongodb-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: question-secrets
                  key: jwt-secret
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: question-config
                  key: port
