apiVersion: v1
kind: Service
metadata:
  name: frontend-lb-service
spec:
  type: LoadBalancer
  selector:
    app: ui
    type: frontend
  ports:
  - protocol: TCP
    port: 60003
    targetPort: 3000

