apiVersion: v1
kind: Service
metadata:
  name: collab-lb-service
spec:
  type: LoadBalancer
  selector:
    app: collaboration
    type: backend
  ports:
  - protocol: TCP
    port: 60002
    targetPort: 5555
